// forbid unsafe code
#![forbid(unsafe_code)]

#![feature(test)]
extern crate test;

mod canvas;
pub mod color;
pub mod errors;
mod point;
pub mod shape;

pub use canvas::Canvas;
pub use color::Color;
pub use point::Point;

/// A type for result generated by Ada
pub type Result<T> = core::result::Result<T, errors::Error>;
